name: CrateKeys
master:
author: MakerbakerYT
version: 1.0.0

author: MakerbakerYT
version: 1.0.0
master:
api: 3.0.0
main: MakerbakerYT\CrateKey\Main

permissions:
  cratekey:
    children:
      cratekey.command:
        children:
          cratekey.command.key:
            default: op
          cratekey.command.keyall:
            default: op
          cratekey.command.keylist:
            default: true
