###############_LANGUAGE_###############

language: eng

###############_KEY-LIST_###############

# Example:
# KeyName:
#   ID: ID of this key
#   Damage: Damage of this key
#   CustomName:  CustomName of this key
#   Description: Description of this key

keys:
  KeyTest:
    ID: 131
    Damage: 0
    CustomName: "§7-=[ §eKeyTest §7]=-"
    Description: "KeyTest Description"
  KeyTest2:
    ID: 131
    Damage: 0
    CustomName: "§7-=[ §cKeyTest2 §7]=-"
    Description: "KeyTest2 Description"

###############_KEY-REWARDS_###############

# Example:
# KeyName:
# - command: Command
#   message: Message to send to player
#   title: Title to send to player
#   subtitle: SubTitle to send to player
#   spawn-item: "id:damage:amount" of the virtual item

rewards:
  KeyTest:
  - command: "tell {player} Comando1"
    message: "Message1"
    title: "Title1"
    subtitle: "SubTitle1"
    spawn-item: "349:0:1"
  - command: "tell {player} Comando2"
    message: "Message2"
    title: "Title2"
    subtitle: "SubTitle2"
    spawn-item: "349:0:1"
  KeyTest2:
  - command: "tell {player} Comando3"
    message: "Message3"
    title: "Title3"
    subtitle: "SubTitle3"
    spawn-item: "349:0:1"
  - command: "tell {player} Comando4"
    message: "Message4"
    title: "Title4"
    subtitle: "SubTitle4"
    spawn-item: "349:0:1"
